export const ADD_INVOICE = "ADD_INVOICE";
export const EDIT_INVOICE = "EDIT_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const SET_SELECTED_INVOICE_ID = "SET_SELECTED_INVOICE_ID";
